# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml
branches:
  only:
    - master

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev
      - texlive-fonts-recommended
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-latex-recommended
      - lhs2tex

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - |
    travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz \
      | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack --no-terminal --install-ghc build --only-dependencies

script:
  # Build the package
  - stack --no-terminal build
  # Convert to LaTeX
  - lhs2TeX src/Paper.lhs -o src/Paper.tex
  # Build the PDF
  - |
    pushd src/
    mkdir -v _tex_build/
    pdflatex -interaction=nonstopmode \
             -halt-on-error \
             -output-directory=_tex_build \
             Paper.tex
    popd

after_script:
  - mkdir -v doc/
  - cp -v src/_tex_build/Paper.{tex,pdf} doc/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: doc
  on:
    branch: master

